# Model settings
val_every: 10
model_checkpoint_interval: 1
seed: 0
model:
  name: LaneATT
  parameters:
    backbone: resnet18
    S: &S 72
    topk_anchors: 1000
    anchors_freq_path: 'data/tusimple_anchors_freq.pt'
    img_h: &img_h 360
    img_w: &img_w 640
batch_size: 8
epochs: 100
loss_parameters: {}
train_parameters:
  conf_threshold:
  nms_thres: 15.
  nms_topk: 3000
test_parameters:
  conf_threshold: 0.2
  nms_thres: 45.
  nms_topk: &max_lanes 5
optimizer:
  name: Adam
  parameters:
    lr: 0.0003
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    T_max: 45400 # 100 * 454 iterations

# Dataset settings
datasets:
  train: &train
    type: LaneDataset
    parameters:
      S: *S
      dataset: tusimple
      split: train+val
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 1.0
      augmentations:
        - name: Affine
          parameters:
            translate_px:
              x: !!python/tuple [-25, 25]
              y: !!python/tuple [-10, 10]
            rotate: !!python/tuple [-6, 6]
            scale: !!python/tuple [0.85, 1.15]
        - name: HorizontalFlip
          parameters:
            p: 0.5

      root: "datasets/tusimple"

  test:
    type: LaneDataset
    parameters:
      S: *S
      dataset: tusimple
      split: test
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 0
      augmentations:
      root: "datasets/tusimple-test"

  val:
    type: LaneDataset
    parameters:
      S: *S
      dataset: tusimple
      split: val
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 0
      augmentations:
      root: "datasets/tusimple"
